XSENS_NAME_MAPPING = {
    "Pelvis": 0,
    "L5": 1,
    "L3": 2,
    "T12": 3,
    "T8": 4,
    "Neck": 5,
    "Head": 6,
    "RightShoulder": 7,
    "RightUpperArm": 8,
    "RightForeArm": 9,
    "RightHand": 10,
    "LeftShoulder": 11,
    "LeftUpperArm": 12,
    "LeftForeArm": 13,
    "LeftHand": 14,
    "RightUpperLeg": 15,
    "RightLowerLeg": 16,
    "RightFoot": 17,
    "RightToe": 18,
    "LeftUpperLeg": 19,
    "LeftLowerLeg": 20,
    "LeftFoot": 21,
    "LeftToe": 22
}
