1:
- !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAABwa0A=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAADQaEA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAABocEA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAACoe0A=
2:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAADqiUA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAADQaEA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAYb0A=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAACoe0A=
3:
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAABsdUA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAABgSUA=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAIa0A=
- !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAACkekA=